// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxsdtxgnayujpvpbxisk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4c2R0eGduYXl1anB2cGJ4aXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDgzOTksImV4cCI6MjA2MzM4NDM5OX0.-7Ka-yNeDTlmIad5aCB73-CGsw78NQmrDiBvSVxFrPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);